mytiki/client-library-ios

TikiClient/Classes/Email/EmailRepository.swift, TikiClient/Classes/Email/EmailService.swift, TikiClient/Classes/KeychainHelper.swift
=> Retrieve connected email accounts

TikiClient/Classes/Email/EmailService.swift
=> Remove email account

TikiClient/Classes/License/LicenseService.swift
closes #20 
closes #21 
closes #22 
closes #23
=> feat: license service

Account/AccountProvider.swift, Account/AccountService.swift, Example/Tests/Tests.swift, Example/TikiClient/Example.swift, TikiClient/Classes/Auth/AuthTokenResponse.swift, TikiClient/Classes/Email/EmailOAuthRefeshTokenResponse.swift, TikiClient/Classes/Email/EmailProviderEnum.swift, TikiClient/Classes/Email/EmailRepository.swift, TikiClient/Classes/Email/EmailService.swift, TikiClient/Classes/KeychainHelper.swift, TikiClient/Classes/License/LicenseService.swift, TikiClient/Classes/Ui/Account/Account.swift, TikiClient/Classes/Ui/Email/EmailLoginOAuth.swift, TikiClient/Classes/Ui/Email/EmailView.swift, TikiClient/Classes/Ui/More/MoreView.swift, TikiClient/Classes/Ui/Rewards.swift
=> Connect Email service with UI

TikiClient/Classes/Email/EmailService.swift, TikiClient/Classes/Util/Extension/DataString.swift
=> Download indexed emails

TikiClient/Classes/Auth/AuthService.swift, TikiClient/Classes/Auth/Token/TokenAuth.swift, TikiClient/Classes/Auth/Token/TokenRequestTask.swift, TikiClient/Classes/Auth/UserAddressRequest.swift, TikiClient/Classes/Util/Extension/UrlSafe.swift
=> Register user address

TikiClient/Classes/License/LicenseRequest.swift, TikiClient/Classes/License/PostLicenseRequest.swift, Use/Use.swift, Use/Usecase.swift, Use/UsecaseCommon.swift
=> Sign the License request

Example/TikiClient.xcodeproj/project.pbxproj, TikiClient.podspec
=> fix: update project

.github/workflows/version.yml, README.md, TikiClient.podspec
Release the permissions feature
=> feature: device permissions

.github/settings.yml
enable projects, disable discussions
=> fix: enable projects

Example/Podfile.lock, Example/TikiClient.xcodeproj/project.pbxproj, TikiClient.podspec, TikiClient/Classes/TikiClient.swift
=> feat/Import AppAuth

TikiClient/Classes/Email/EmailService.swift
=> feat/Scrape and Publish PDF receipts

TikiClient.podspec
=> fix: bump version

TikiClient/Classes/License/LicenseUse.swift, TikiClient/Classes/License/LicenseUseCase.swift, TikiClient/Classes/License/LicenseUseCaseEnum.swift, TikiClient/Classes/Rewards.swift, TikiClient/Classes/TitleTag.swift, TikiClient/Classes/TitleTagEnum.swift, TikiClient/Classes/Trail/LicenseRecord.swift, TikiClient/Classes/Trail/PayableRecord.swift, TikiClient/Classes/Trail/Rsp/RspLicense.swift, TikiClient/Classes/Trail/Rsp/RspPayable.swift, TikiClient/Classes/Trail/Rsp/RspTitle.swift, TikiClient/Classes/Trail/Tag.swift, TikiClient/Classes/Trail/TagCommon.swift, TikiClient/Classes/Trail/TitleRecord.swift, TikiClient/Classes/UI/Bullet.swift, TikiClient/Classes/UI/Offer.swift, TikiClient/Classes/UI/OfferFlow.swift, TikiClient/Classes/UI/OfferFlowSteps.swift, TikiClient/Classes/UI/Screens/OfferPrompt.swift, TikiClient/Classes/Util/Rsp.swift
=> feat/Create Offer class

TikiClient/Classes/License/LicenseUse.swift, TikiClient/Classes/Reward.swift, TikiClient/Classes/RewardCommon.swift, TikiClient/Classes/TikiClient.swift, TikiClient/Classes/UI/Offer.swift
=> feat/Func CreateOffer

TikiClient/Classes/TikiClient.swift
=> feat/Logic to accept an Offer

TikiClient/Classes/TikiClient.swift
=> Feat/logic to denied an offer 

README.md, TikiClient.podspec
=> feature: optin rates

TikiClient/Classes/OptInService.swift, TikiClient/Classes/UI/OfferStepFollow.swift
=> feat/Create OptInService class

TikiClient/Classes/OptInService.swift, TikiClient/Classes/TikiClient.swift, TikiClient/Classes/UI/Offer.swift, TikiClient/Classes/UI/OfferFlow.swift, TikiClient/Classes/UI/OfferFlowSteps.swift, TikiClient/Classes/UI/Screens/OfferAllowTraking.swift, TikiClient/Classes/UI/Screens/OfferLinkCardView.swift, TikiClient/Classes/UI/Screens/SettingsDetailsView.swift, TikiClient/Classes/UI/Screens/SettingsTableView.swift, TikiClient/Classes/UI/Screens/SettingsView.swift
=> Feat/the developer can set which offer can be changed 

.github/settings.yml, Example/Podfile.lock, Example/TikiClient.xcodeproj/project.pbxproj, README.md, TikiClient.podspec
=> feat: optin
